services:
  - type: web
    name: djfriend
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build && npm run build:server
    startCommand: node server-compiled/standalone-server.js
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
